name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App URL
        run: curl -s -o /dev/null -w "Status Code: %{http_code}\n" https://csp-fy27-kickoff.streamlit.app/
